1-install_load_balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,16 +1,29 @@
 #!/usr/bin/env bash
-#Installs and configures HAproxy in a load balancer server
+# Installs and configures HAproxy in a load balancer server
 
+# Check if the script is being run as root
+if [ "$(id -u)" -ne 0 ]; then
+    echo "Error: Script must be run as root"
+    exit 1
+fi
+
+# Install required packages
+apt-get update
 apt-get install -y software-properties-common
 add-apt-repository -y ppa:vbernat/haproxy-1.8
 apt-get update
-apt-get install -y haproxy=1.8.\*
+apt-get install -y haproxy=1.8.*
 
+# Enable HAProxy
 echo "ENABLED=1" >> /etc/default/haproxy
-mv /etc/haproxy/haproxy.cfg{,.original}
+
+# Create HAProxy configuration file
+mv /etc/haproxy/haproxy.cfg{,.original} || true
 touch /etc/haproxy/haproxy.cfg
 
-printf %s "global
+# Populate HAProxy configuration file
+cat << EOF > /etc/haproxy/haproxy.cfg
+global
     log 127.0.0.1 local0 notice
     maxconn 2000
     user haproxy
@@ -35,6 +48,8 @@ listen hbnb
     option forwardfor
     server 59637-web-01 54.160.85.72:80 check
     server 59637-web-02 35.175.132.106:80 check
-" >> /etc/haproxy/haproxy.cfg
+EOF
 
+# Start HAProxy service
 service haproxy start
+
